# 本地配置
server:
  port: 8080
# spring 配置
spring:
  application:
    name: cloud-tracing
# 链路追踪 jaeger
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    const-sampler:
      decision: true
    udp-sender:
      host: wxw.plus
      port: 6831
    service-name: cloud-jaeger-tracing